version: "3.7"

services:
  laravel:
    image: lucdijkstra/ikdock_backend:latest
    networks:
      - backend
    volumes:
      - ./src/backend/:/src/
    environment:
      - APP_KEY=base64:0CXp/UKPg1IeXT3FC/nRZGU4puSnRVgFME2o80UYfpM=
    depends_on:
      - database
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
      restart_policy:
        condition: any
        delay: 2s
        window: 10s

  database:
    image: lucdijkstra/ikdock_mariadb:latest
    networks:
      - backend
    environment:
      - MYSQL_DATABASE=eurovision
      - MYSQL_ROOT_PASSWORD=wachtwoord123
      - MYSQL_USER=duncan
      - MYSQL_PASSWORD=lawrence
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: any
        delay: 2s
        window: 120s

  react:
    image: lucdijkstra/ikdock_frontend:latest
    networks:
      - frontend
    volumes:
      - ./docker/react/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/react/sites/:/etc/nginx/sites-available
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
      restart_policy:
        condition: any
        delay: 2s
        window: 10s

  nginx:
    image: lucdijkstra/ikdock_nginx:latest
    volumes:
      - ./src/backend/:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "8000:8000"
    networks:
      - frontend
      - backend
    depends_on:
      - react
      - laravel
    deploy:
      mode: replicated
      restart_policy:
        condition: any
        delay: 2s
        window: 10s

  migrations:
    image: lucdijkstra/ikdock_migrations:latest
    environment:
      - MYSQL_USER=duncan
      - MYSQL_PASSWORD=lawrence
    networks:
      - backend
    depends_on:
      - database
    deploy:
      restart_policy:
        condition: none

networks:
  frontend:
    driver: overlay
    attachable: true
  backend:
    driver: overlay
    attachable: true
